version: '3.8'

services:
  # Django ilovasi
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8004
    volumes:
      - .:/app
    ports:
      - "8004:8004"
    depends_on:
      - redis
      - db
    networks:
      - app_network2

  # telegram bot
  bot:
    build: .
    command: python bot/main.py
    volumes:
      - .:/app

  # Celery worker
  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app_network2

  # Celery beat
  celerybeat:
    build: .
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app_network2

  # Redis (broker)
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app_network2

  # Database
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5435:5432"
    env_file:
      - .env
    networks:
      - app_network2

networks:
  app_network2:
